ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - esbuild
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - "@next/*"
  - eslint-config-next
  - next
